---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: namespace-listing-role
rules:
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["list", "get"]
  - apiGroups: [""]
    resources: ["pods", "pods/log"]
    verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: namespace-listing-role-binding
subjects:
  - kind: ServiceAccount
    name: default # update to desired name
    namespace: default # update to your desired namespace
roleRef:
  kind: ClusterRole
  name: namespace-listing-role
  apiGroup: rbac.authorization.k8s.io
